id = 1
name = "Home"
defaultRoom = { areaId = 1, id = 1 }

[[rooms]]
id = 1
name = "Entrance"
description = "Your home entrance. A $gflower pot$* is standing on the windowsill."
staticObjects = [3]

[rooms.exits]
north = { areaId = 1, id = 2 }
south = { areaId = 2, id = 1 }

[[rooms]]
id = 2
name = "Bedroom"
description = "Your bedroom."
staticObjects = [4]

[rooms.exits]
south = { areaId = 1, id = 1 }
