id = 1
name = "Home"
defaultRoom = { areaId = 1, id = 1 }
unload = "never"

[[rooms]]
id = 1
name = "Entrance"
description = "Your home entrance. A $gflower pot$* is standing on the windowsill."

[rooms.exits]
north = { areaId = 1, id = 2 }
south = { areaId = 2, id = 3 }
east = { areaId = 1, id = 3 }


[[rooms]]
id = 2
name = "Bedroom"
description = "Your bedroom."

[[rooms.placedItems]]
id = 1001

[[rooms.placedItems]]
id = 1002

[rooms.exits]
south = { areaId = 1, id = 1 }


[[rooms]]
id = 3
name = "Kitchen"
description = "The kitchen."

[rooms.exits]
west = { areaId = 1, id = 1 }


[[rooms]]
id = 4
name = "Outhouse"
description = "A smelly place."

[rooms.exits]
south = { areaId = 2, id = 1 }
