id = 3
name = "Town"
defaultRoom = { areaId = 3, id = 1 }
unload = "never"

[[rooms]]
id = 1
name = "Town square"
description = "Central square. Shops to the north."

[rooms.exits]
north = { areaId = 3, id = 2 }
west = { areaId = 2, id = 1 }


[[rooms]]
id = 2
name = "Shop"
description = "They sell farm tools and seeds here."

[rooms.exits]
south = { areaId = 3, id = 1 }

[[rooms.placedActors]]
id = 1001

[[rooms.placedActors]]
id = 1002


[[shops]]
id = 1
room = { areaId = 3, id = 2 }
shopkeeps = [1001, 1002]
buyTags = ["seed", "produce", "food"]

[[shops.items]]
id = 4001
count = -1

[[shops.items]]
id = 3001
count = 1

[[shops.items]]
id = 3002
count = 1
