id = 4
name = "Trail"
unload = "overnight"

[[rooms]]
id = 1
name = "Trail"
description = """
The trail is covered in grass here. In fact, it barely looks like a trail \
since so few people actually visit your cottage. To the east the trail becomes more pronounced, \
you can see the town rooftops further away."""

[rooms.exits]
west = { areaId = 2, id = 8 }
east = { areaId = 4, id = 2 }


[[rooms]]
id = 2
name = "Trail"
description = """
You're walking on a trail between your cottage and the town. You see someone \
further in the field. They might be looking for a good picnic spot, or maybe foraging. Better \
leave them to it."""

[rooms.exits]
west = { areaId = 4, id = 1 }
east = { areaId = 4, id = 3 }

[[rooms.placedItems]]
id = 9


[[rooms]]
id = 3
name = "Fork in the road"
description = """
The trail turns northward, to the river. You hear faint sounds of \
running water that way. Further east the trail transforms into a stone road, leading \
towards the town."""

[rooms.exits]
west = { areaId = 4, id = 2 }
east = { areaId = 4, id = 4 }
north = { areaId = 5, id = 3 }


[[rooms]]
id = 4
name = "Road"
description = """One stone, two stone... five hundreds seventy three stone. Walking down this \
road is boring. Laying all these stones might've been even more boring. But thanks yo whomever \
spent their time and energy doing this, you can cover much bigger distance faster. Dang, \
which stone was it, five hundreds seventy forth?"""

[rooms.exits]
west = { areaId = 4, id = 3 }
east = { areaId = 4, id = 5 }


[[rooms]]
id = 5
name = "Town road"
description = """
Stone road outside of town. Far to the west, hidden among weeds and bushes, you can \
see you cottage. A road, turning into a dirt trail leads to it. Right here to the east \
is the town."""

[rooms.exits]
west = { areaId = 4, id = 4 }
east = { areaId = 6, id = 1 }


