id = 2
name = "Yard"
defaultRoom = { areaId = 2, id = 1 }
unload = "never"

[[rooms]]
id = 1
name = "In front of the house"
description = "You're in front of your house."

[[rooms.placedItems]]
id = 2003

[[rooms.placedItems]]
id = 2005

[[rooms.placedItems]]
id = 6
containerId = 2005

[[rooms.placedItems]]
id = 4003
containerId = 2003

[rooms.exits]
north = { areaId = 1, id = 1 }
