id = 2
name = "Yard"
defaultRoom = { areaId = 2, id = 1 }

[[rooms]]
id = 1
name = "In front of the house"
description = "You're in front of your house."

[[rooms.placedItems]]
id = 2001
[[rooms.placedItems]]
id = 2002
[[rooms.placedItems]]
id = 2003
[[rooms.placedItems]]
id = 2004

[rooms.exits]
north = { areaId = 1, id = 1 }
