[[articles]]
name = "Common Commands"
terms = ["", "help"]
description = """
Type $Yhelp [command]$* for more details about each command.
When entering a command, there's no need to type its full name.

Looking around: $Ylook, scan, inventory$*.
Movement commands: $Ynorth, east, south, west$*.
Item interaction: $Ytake, drop, put, fill$*.
NPC interaction: $Ygive, buy, sell$*.
See also: $Yfarming, foraging, sleep, quit$*."""
references = ["farming", "foraging", "trading", "sleep"]


[[articles]]
name = "Look"
terms = ["look"]
format = """
look
look <item>
take <order>.<item>"""
example = """
look
look box
look 2.tool"""
description = """
Looking is the most important command in your arsenal. It allows you to receive details about \
your current location, or to inspect items on the ground and in your inventory. Looking at \
a container or vessel will inform you about its contents. Looking at a tool will let you \
know how damaged it is.

$Y"look"$* will display the description of your current location along with the full list \
of items on the ground.
$Y"look apple"$* will show the details of the first available apple in your inventory or \
on the ground.
$Y"look 3.tool"$* will show the details of the third available tool in your inventory or \
on the ground."""
references = ["inventory", "scan", "where"]


[[articles]]
name = "Inventory"
terms = ["inventory"]
format = """
inventory [filter]"""
example = """
inventory
inv
inv seed"""
description = """
This command shows the list of items in your inventory, which you have $Ytake$*n before. \
Supplying an optional filter word optionally will result in only items, which have this \
word in their name, showing up.

$Y"inventory"$* will display all currently held items.
$Y"inventory seed"$* will show all currently held seeds."""
references = ["take", "drop", "look"]