[[articles]]
name = "Take"
terms = ["take", "get"]
format = """
take <item> [container]
take <order>.<item> [container]
take <quantity>*<item> [container]
take <quantity>*<order>.<item> [container]"""
example = """
take apple
t 5*app

take apple box
take 2.tool box
take 2*3.seed box"""
description = """
Lets you take an item or items from the ground or, optionally, a container. Taken item(s) will \
appear in your inventory. Some objects can not be taken, even if they appear \
as items in the world.

$Y"take apple"$* will take the first available apple from the ground.
$Y"take 3.tool"$* will take the third tool from the ground, if available.
$Y"take 5*apple box"$* will take up to five apples from the box.
$Y"take 10*2.seed box"$* will take up to ten seeds from the second seed stack in the box."""
references = ["inventory", "put", "drop"]


[[articles]]
name = "Put"
terms = ["put"]
format = """
put <item> <container>
put <order>.<item> <container>
put <quantity>*<item> <container>
put <quantity>*<order>.<item> <container>"""
example = """
put apple
p 5*app

put apple box
put 2.tool box
put 2*3.seed box"""
description = """
Lets you put an item or items inside a container. The specified item must be \
in your inventory. The container must be capable of holding items. Liquid containers \
can't receive items this way and must be filled from sources. To put an item on \
the ground, use $Ydrop$*.

$Y"put apple box"$* will put the first available apple into the box.
$Y"put 3.tool box"$* will put the third tool from your inventory into the box.
$Y"put 5*apple box"$* will put up to five apples into the box.
$Y"put 10*2.seed box"$* will put up to ten seeds from the second seed stack in your inventory \
into the box."""
references = ["inventory", "take", "drop", "fill"]


[[articles]]
name = "Drop"
terms = ["drop"]
format = """
drop <item>
drop <order>.<item>
drop <quantity>*<item>
drop <quantity>*<order>.<item>"""
example = """
drop apple
dr 5*app

drop apple box
drop 2.tool box
drop 2*3.seed box"""
description = """
Lets you drop an item or items on the ground. The specified item must be \
in your inventory. Dropped items will appear on the ground, and will be visible \
when $Ylook$*ing around.

Be careful when dropping items outside of your house. They will $Rdisappear$* after \
some time. Items inside your house are safe.

$Y"drop apple"$* will drop the first available apple.
$Y"drop 3.tool"$* will drop the third tool from your inventory on the ground.
$Y"drop 5*apple"$* will drop up to five apples.
$Y"drop 10*2.seed"$* will drop up to ten seeds from the second seed stack in your inventory."""
references = ["inventory", "take", "look"]


[[articles]]
name = "Fill"
terms = ["fill"]
format = """
fill <vessel> <source>"""
example = """
fill rusty pond"""
description = """
Fills a vessel with a liquid. If the vessel already contains the same liquid, \
this command will top it up. If there's a different liquid in the vessel, it needs to be \
pured first."""
references = ["pour", "water"]


[[articles]]
name = "Pour"
terms = ["pour"]
format = """
pour <vessel>"""
example = """
pour watering"""
description = """
Empties out a liquid container. Empty vessel can then be filled with liquid. \
There's no need to empty a vessel if you want to fill it with more of the same liquid."""
references = ["fill"]