[[items]]
id = 4000
name = "$yDe$gad $rpl$yan$gt$*"
tags = ["plant", "junk"]
basePrice = 0.0

[[items.transformations]]
targetId = 4000
action = "uproot"


[[items]]
id = 4001
name = "Potato seeds"
tags = ["potato", "seed", "seeds"]
basePrice = 2.0

[[items.transformations]]
targetId = 4002
containerId = 2004
action = "grow"
step = 0.5

[[items.transformations]]
targetId = 4000
containerId = 2003
action = "wilt"
step = 0.25

[[items.transformations]]
targetId = 4001
action = "uproot"


[[items]]
id = 4002
name = "Potato seedling"
nouns = ["seedling"]
tags = ["plant", "fodder"]

[[items.transformations]]
targetId = 4003
containerId = 2004
action = "grow"
step = 0.34

[[items.transformations]]
targetId = 4000
containerId = 2003
action = "wilt"
step = 0.25

[[items.transformations]]
targetId = 4000
action = "uproot"


[[items]]
id = 4003
name = "Potato plant"
tags = ["potato", "plant"]

[[items.transformations]]
targetId = 4004
action = "harvest"

[[items.transformations]]
targetId = 4000
containerId = 2004
action = "wilt"
step = 0.2


[[items]]
id = 4004
name = "Potato"
tags = ["fruit", "produce", "food"]
basePrice = 25.0


[[items]]
id = 4005
name = "Beetroot seeds"
tags = ["seed"]
basePrice = 4.0

[[items.transformations]]
targetId = 4006
containerId = 2004
action = "grow"
step = 0.5

[[items.transformations]]
targetId = 4000
containerId = 2003
action = "wilt"
step = 0.25

[[items.transformations]]
targetId = 4005
action = "uproot"


[[items]]
id = 4006
name = "Beetroot seedling"
nouns = ["seedling"]
tags = ["plant", "fodder"]

[[items.transformations]]
targetId = 4007
containerId = 2004
action = "grow"
step = 0.25

[[items.transformations]]
targetId = 4000
containerId = 2003
action = "wilt"
step = 0.25

[[items.transformations]]
targetId = 4000
action = "uproot"


[[items]]
id = 4007
name = "Beetroot plant"
tags = ["plant"]

[[items.transformations]]
targetId = 4008
action = "harvest"

[[items.transformations]]
targetId = 4000
containerId = 2004
action = "wilt"
step = 0.2


[[items]]
id = 4008
name = "Beetroot"
tags = ["fruit", "produce", "food"]
basePrice = 43.0