[[items]]
id = 1001
name = "Bed"
roomDescription = "An old bed is standing here."
description = """
An old bed, passed on by the previous owners of this place. \
It's a wooden, creaking piece of furniture. \
The mattress is old and lumpy. Coarse sheets became almost \
beige with age. Covered with a red, brown and \
black plaid blanket. It's not the best bed in the world, \
but it's always here, whether you need a quick nap \
or a proper $Gsleep$* after a day of hard work."""
flags = ["nopickup", "nohide"]
tags = ["bed", "furniture", "uncomfortable"]


[[items]]
id = 1002
name = "Wardrobe"
roomDescription = "A tall and wide wardrobe takes an entire wall."
description = """
A wardrobe with lots of shelves and compartments. Unlike the rest of the old furniture, \
this wardrobe looks actually antique.  You can $Gput$* something \
inside or $Gtake$* something out of it."""
flags = ["nopickup", "nohide", "container"]
tags = ["furniture"]


[[items]]
id = 1003
name = "Box"
roomDescription = "A big box, capable of holding items."
description = "A big wooden box with a lid. You can $Gput$* something in it, if you need to free up your hands. You can always $Gtake$* your items back later."
flags = ["nopickup", "nohide", "container"]
tags = ["furniture"]


[[items]]
id = 1004
name = "Well"
roomDescription = "A $Bwater well$* was dug up here."
description = """
A narrow but deep freshwater well. You can $Gfill $*something with water here."""
flags = ["nopickup", "nohide", "nointeract", "source", "container"]