
[[items]]
id = 1
name = "Pebble"

[[items]]
id = 2
name = "Apple"
tags = ["fruit", "produce", "food"]

[[items]]
id = 3
name = "$gFlowerpot"
flags = ["nopickup", "nolist"]

[[items]]
id = 5
name = "$BPond"
roomDescription = "$YThere's a small $Bpond $Yof fresh water."
description = "A small pond with fresh water. You can $Yfill $*something with water here. Or just relax."
flags = ["nopickup", "nohide"]
