
[[items]]
id = 1
name = "Pebble"

[[items]]
id = 2
name = "Apple"
tags = ["fruit", "produce", "food"]

[[items]]
id = 3
name = "$gFlowerpot"
flags = ["nopickup", "nolist"]

[[items]]
id = 6
name = "Water"
flags = ["nopickup", "liquid"]
