[[items]]
id = 2001
name = "Dry soil"
roomDescription = "$yDry soil"
flags = ["nopickup", "nohide"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2003
action = "till"

[[items.transformations]]
targetId = 2002
action = "water"


[[items]]
id = 2002
name = "Wet soil"
roomDescription = "$yWet soil"
flags = ["nopickup", "nohide"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2004
action = "till"

[[items.transformations]]
targetId = 2001
action = "overnight"


[[items]]
id = 2003
name = "Dry tilled soil"
roomDescription = "$yDry tilled soil"
flags = ["nopickup", "nohide", "container", "nointeract"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2004
action = "water"

[[items.transformations]]
targetId = 2001
action = "overnight"
step = 0.34
contents = []


[[items]]
id = 2004
name = "Wet tilled soil"
roomDescription = "$yWet tilled soil"
flags = ["nopickup", "nohide", "container", "nointeract"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2003
action = "overnight"


[[items]]
id = 2005
name = "$BPond"
roomDescription = "$wThere's a small $Bpond $wof fresh water."
description = "A small pond with fresh water. You can $Gfill $*something with water here."
flags = ["nopickup", "nohide", "nointeract", "source", "container"]
