[[items]]
id = 2001
name = "Dry soil "
nouns = ["soil", "patch"]
roomDescription = "$yA patch of dry soil waiting to be tilled and watered."
flags = ["nopickup", "nohide"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2003
action = "till"

[[items.transformations]]
targetId = 2002
action = "water"


[[items]]
id = 2002
name = "Wet soil"
nouns = ["soil", "patch"]
roomDescription = "$yA patch of wet soil."
flags = ["nopickup", "nohide"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2004
action = "till"

[[items.transformations]]
targetId = 2001
action = "overnight"


[[items]]
id = 2003
name = "Dry tilled soil"
nouns = ["soil", "patch", "tilled"]
roomDescription = "$yDry tilled soil patch."
flags = ["nopickup", "nohide", "container", "nointeract"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2004
action = "water"

[[items.transformations]]
targetId = 2001
action = "overnight"
step = 0.34
contents = []


[[items]]
id = 2004
name = "Wet tilled soil"
nouns = ["soil", "patch", "tilled"]
roomDescription = "$yA patch of wet tilled soil, perfect for plant growth."
flags = ["nopickup", "nohide", "container", "nointeract"]
tags = ["terrain"]

[[items.transformations]]
targetId = 2003
action = "overnight"
