[[items]]
id = 3001
name = "Hoe"
description = "A tool used for $Gtill$*ing soil."
tags = ["tool"]
flags = ["nostack"]
basePrice = 300.0


[[items]]
id = 3002
name = "Watering can"
capacity = 50
tags = ["tool"]
flags = ["nostack", "container", "nointeract", "vessel"]
basePrice = 300.0